checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@mikro-orm/knex@*":
    dependencies:
      pg: "*"
  ra-ui-materialui@*:
    dependencies:
      "@mui/utils": "*"
      react-is: "*"
  react-tracked@*:
    dependencies:
      scheduler: "*"

supportedArchitectures:
  cpu:
    - x64
  os:
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.5.0.cjs
