plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  os:
    - linux
    - win32
  cpu:
    - x64

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  ra-i18n-polyglot@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
      react-hook-form: "*"
      react-router: "*"
      react-router-dom: "*"
      history: "*"
  ra-language-english@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
      react-hook-form: "*"
      react-router: "*"
      react-router-dom: "*"
      history: "*"
  ra-ui-materialui@*:
    dependencies:
      react-is: "*"