checksumBehavior: update

packageExtensions:
  ra-i18n-polyglot@*:
    peerDependencies:
      history: "*"
      react: "*"
      react-dom: "*"
      react-hook-form: "*"
      react-router: "*"
      react-router-dom: "*"
  ra-language-english@*:
    peerDependencies:
      history: "*"
      react: "*"
      react-dom: "*"
      react-hook-form: "*"
      react-router: "*"
      react-router-dom: "*"
  ra-ui-materialui@*:
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  cpu:
    - x64
  os:
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.0.0-rc.49.cjs
