packageExtensions:
  stylelint-config-recommended-scss@*:
    peerDependencies:
      postcss: "*"
  stylelint-config-standard-scss@*:
    peerDependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

supportedArchitectures:
  os:
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.2.1.cjs
