checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  ra-ui-materialui@*:
    dependencies:
      react-is: "*"
  "@mikro-orm/knex@*":
    dependencies:
      pg: "*"

supportedArchitectures:
  cpu:
    - x64
  os:
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.0.2.cjs
