checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@mikro-orm/knex@*":
    dependencies:
      pg: "*"
  ra-core@*:
    dependencies:
      react: "*"
      react-dom: "*"
      react-hook-form: "*"
      react-router: "*"
      react-router-dom: "*"
  ra-ui-materialui@*:
    dependencies:
      "@mui/utils": "*"
      react-is: "*"
      "@mui/system": "*"
      csstype: "*"
  react-tracked@*:
    dependencies:
      scheduler: "*"
      react: "*"
  use-context-selector@*:
    dependencies:
      react: "*"
      react-dom: "*"
  jotai-immer@*:
    dependencies:
      react: "*"
      react-dom: "*"
  jotai@*:
    dependencies:
      react: "*"
      react-dom: "*"
  jotai-devtools@*:
    dependencies:
      react-dom: "*"
  "@mui/styled-engine@*":
    dependencies:
      "@emotion/styled": "*"
      "@emotion/react": "*"

supportedArchitectures:
  cpu:
    - x64
  os:
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.11.0.cjs
