checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@mikro-orm/knex@*":
    dependencies:
      pg: "*"
  ra-ui-materialui@*:
    dependencies:
      react-is: "*"

supportedArchitectures:
  cpu:
    - x64
  os:
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.1.1.cjs
