checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "ra-ui-materialui@*":
    peerDependencies:
      'react-is': "*"


supportedArchitectures:
  cpu:
    - x64
  os:
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.0.0-rc.49.cjs
