yarnPath: .yarn/releases/yarn-3.2.1.cjs
packageExtensions:
  "stylelint-config-recommended-scss@*":
    peerDependencies:
      postcss: "*"
  "stylelint-config-standard-scss@*":
    peerDependencies:
      postcss: "*"
supportedArchitectures:
  os:
    - "linux"
    - "win32"