name: "Setup Node"
description: "Setup Node and build Common"
inputs:
  node-version:
    required: true
    description: "Node version"

runs:
  using: "composite"
  steps:
    - name: Use Node
      id: node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
    - name: Common deps and build
      shell: bash
      run: |
        yarn workspaces focus common
        yarn workspace common build
