name: Deploy Website to Staging

on:
  push:
    branches: [ "staging" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Build and push
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: kamiyo/sycpiano:latest
    - name: Create Tunnel to DB
      run: |
        mkdir -p ~/.ssh
        ${{ secrets.SSH_ED25519 }} > id_ed25519
        ssh deploy@ssh.seanchenpiano.com
    # - name: Migration
    #   uses: addnab/docker-run-action@v3
    #   with:
    #     image: amacneil/dbmate
    #     options: -v ${{ github.workspace }}:/workspace
